### ISSUE TITLE
Can't get the container to run reliably

### ISSUE THREAD

**Issue by heffneil** [sclaflin/Plate-Minder#37]
I had several issues getting things to work and through hodgepodge I was able to determine how to configure things in with docker compose - where it was running but now it will not run.  Below are the errors I receive in logs:

```
today at 11:55:53 AMalways restart: false
today at 1:57:47 PMnpm ERR! path /app
today at 1:57:47 PMnpm ERR! command failed
today at 1:57:47 PMnpm ERR! signal SIGTERM
today at 1:57:47 PMnpm ERR! command sh -c -- node index.js
today at 1:57:47 PM
today at 1:57:47 PMnpm ERR! A complete log of this run can be found in:
today at 1:57:47 PMnpm ERR!     /home/app/.npm/_logs/2024-09-10T15_55_51_112Z-debug-0.log
today at 1:58:29 PM
today at 1:58:29 PM> plate-minder@0.2.2 start
today at 1:58:29 PM> node index.js
today at 1:58:29 PM
today at 1:58:32 PMalways restart: false
today at 2:04:47 PMnpm ERR! path /app
today at 2:04:47 PMnpm ERR! command failed
today at 2:04:47 PMnpm ERR! signal SIGTERM
today at 2:04:47 PMnpm ERR! command sh -c -- node index.js
today at 2:04:47 PM
today at 2:04:47 PMnpm ERR! A complete log of this run can be found in:
today at 2:04:47 PMnpm ERR!     /home/app/.npm/_logs/2024-09-10T17_58_29_936Z-debug-0.log
today at 2:04:48 PM
today at 2:04:48 PM> plate-minder@0.2.2 start
today at 2:04:48 PM> node index.js
today at 2:04:48 PM
today at 2:04:50 PMalways restart: false
today at 2:04:50 PMalways restart: false
today at 2:04:50 PMalways restart: false
today at 2:04:50 PMalways restart: false
today at 2:04:50 PMalways restart: false
today at 2:04:50 PMalways restart: false
today at 2:04:50 PMalways restart: false
```

I don't know what the problem is but the other two containers for the other services are running but I get an error saying Error
Failed to fetch but I believe this is because the plate-minder service will not run.

docker compose yaml:

```
 plate-minder:
    container_name: plate-minder
    restart: unless-stopped
    image: sclaflin/plate-minder:latest
    ports:
      - 4000:4000
    environment:
      - TZ=America/New_York
    volumes:
      # Set's the docker container to the host container local time
      - /etc/localtime:/etc/localtime:ro
      - /home/neil/docker/data/plate-minder/data:/app/data
      - /home/neil/docker/data/plate-minder/config.yaml:/app/config.yaml
    # For Intel related hardware acceleration, the container needs the same
    # group id as /dev/dri/renderD128.
  open-alpr-http-wrapper:
    container_name: open-alpr-http-wrapper
    restart: unless-stopped
    image: sclaflin/open-alpr-http-wrapper:latest
    ports:
      - 3000:3000
  plate-minder-web:
    container_name: plate-minder-web
    image: sclaflin/plate-minder-web:latest
    restart: unless-stopped
    # The default configuration assumes docker is running on the same machine
    # you're viewing the web UI with. If you're accessing the service from a
    # different computer, you should set the PLATE_MINDER_URL to whatever host
    environment:
      - PLATE_MINDER_URL=http://localhost:4000
    ports:
      - 8080:80
```
