### ISSUE TITLE
docker container won't stay running more than 5-10 seconds

### ISSUE THREAD

**Issue by jonadis** [sclaflin/Plate-Minder#4]
Greetings,

First off let me say this is an exciting project and I can't wait to get rolling on this.  That being said perhaps my haste has made waste.
I'm trying to get things up and running using the provided docker-compose.yml with a few minor tweaks but I'm off to a bad start.  The container only starts for about 5-10 seconds then restarts.  I tried looking at the logs of the container with 'docker logs' but I just get a screen full of random characters.  Also, in the ad-hoc docker commands I see port 3000 is exposed for the open-alpr-http-wrapper but it is not in the docker-compose example.  Does port 3000 need to be exposed or can it work container-to-container?

```
version: "3.9"

services:
  plate-minder:
    container_name: plate-minder
    restart: unless-stopped
    image: sclaflin/plate-minder:latest
    ports:
      - 4000:4000
    volumes:
      # Set's the docker container to the host container local time
      - /etc/localtime:/etc/localtime:ro
      - ./plate-minder/data:/app/data
      - ./plate-minder/config.yaml:/app/config.yaml
  open-alpr-http-wrapper:
    container_name: open-alpr-http-wrapper
    restart: unless-stopped
    image: sclaflin/open-alpr-http-wrapper:latest
```

Thanks,
Jon

**Comment by sclaflin** [comment]
Hey Jon!

Glad you're excited about the project. My first thought is folder permissions are probably an issue.

The plate-minder image runs under uid 1000 and **not root**. Check the volumes you're mounting (`./plate-minder/data`& `./plate-minder/config.yaml` to make sure they are owned by uid 1000.

**Comment by sclaflin** [comment]
...and I missed your other questions.

> I tried looking at the logs of the container with 'docker logs' but I just get a screen full of random characters.

Unfortunately, that big ugly wall of text is coming from OpenCV. At the end of it all is often a more useful error message. 

> Does port 3000 need to be exposed or can it work container-to-container?

No, it's not needed when using docker-compose.  One of the benefits to using docker-compose is it will create a network and include all the services in it.  open-alpr-http-wrapper is definitely listening on port 3000 and the other services within it's network can communicate with it just fine. When just spinning up docker containers, we need to explicitly map port 3000 (you could also manually create a network and add all your docker containers to it instead of mapping port 3000).

**Comment by dison4linux** [comment]
Thanks for the reply.  After fixing the permissions of the "data" directory the container starts and runs now.

**Comment by jseidl** [comment]
I'm on the same situation although I've tried both with an empty `config.yaml` and properly configured (to the best of my knowledge) one and it failed to do anything other than spit the openCV blob. I did a `chown -R 1000 /data/plateminder`.

Here's my docker compose:
```
version: "2"  <--- Portainer limitation
services:
  plate-minder:
    container_name: plate-minder
    restart: unless-stopped
    image: sclaflin/plate-minder:latest
    ports:
      - 5014:4000
    volumes:
      # Set's the docker container to the host container local time
      - /etc/localtime:/etc/localtime:ro
      - ./data/plateminder/data:/app/data
      - ./data/plateminder/config.yaml:/app/config.yaml
  open-alpr-http-wrapper:
    container_name: open-alpr-http-wrapper
    restart: unless-stopped
    image: sclaflin/open-alpr-http-wrapper:latest
  # This service is not required, but exists to help with configuration. Once 
  # Plate-Minder has been configured, feel free to disable this service.
  plate-minder-web:
    container_name: plate-minder-web
    image: sclaflin/plate-minder-web:latest
    restart: unless-stopped
    # The default configuration assumes docker is running on the same machine 
    # you're viewing the web UI with. If you're accessing the service from a
    # different computer, you should set the PLATE_MINDER_URL to whatever host 
    # & port Plate-Minder's RESTful service is accessible from.
    environment:
      - PLATE_MINDER_URL=http://plate-minder:5014
    ports:
      - 5018:80

```

Another question I have is that I have MJPEG streams but PlateMinder doesn't have a MJPEG stream source, even thou it consumes MJPEG Streams in the flow. Is there currently a way to consume MJPEG streams as sources? Code didn't seemed like it. 

Cheers!
