### ISSUE TITLE
docker desktop for windows issue

### ISSUE THREAD

**Issue by adamkhanmian** [sclaflin/Plate-Minder#7]
Hi!

I have everything working yet SQLite DB doesn't get updated nor do any images show up in the data folder. Config is made via web interface. I even walked past with a number plate in hand but nothing got recorded.  container info is atached as an image and config is given below. Stream is fine in VLC. (docker-compose didnt assign a port to open-alpr-http-wrapper, so i added 3000 there as it didnt do anything without it either, so i thought maybe this was the issue, although in the open-alpr-http-wrapper container config file port was 3000)

Config file
```
sources:
  - type: rtsp
    name: School Front Gate
    captureInterval: 1
    preInputArgs: []
    preOutputArgs: []
    url: rtsp://XXXX
  - type: rtsp
    name: MussanifOffice front
    captureInterval: 1
    preInputArgs: []
    preOutputArgs: []
    url: rtsp://XXXX
  - type: rtsp
    name: Gate Inside
    captureInterval: 1
    preInputArgs: []
    preOutputArgs: []
    url: rtsp://XXXX
  - type: rtsp
    name: mussanif SD stream
    captureInterval: 1
    preInputArgs: []
    preOutputArgs: []
    url: rtsp://XXXX
filters: []
openALPR:
  url: http://open-alpr-http-wrapper:3000/detect
recorders:
  - type: sqlite
  - type: file
    pattern: ./data/images/{{DATE}}/{{SOURCE}}/{{TIME}}_{{PLATE}}.jpeg
    retainDays: 30
restService:
  enable: true
  port: 4000
```

docker-compose file
```
version: "3.9"
services:
  plate-minder:
    container_name: plate-minder
    restart: unless-stopped
    image: sclaflin/plate-minder:latest
    ports:
      - 4000:4000
    volumes:
      # Set's the docker container to the host container local time
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
  open-alpr-http-wrapper:
    container_name: open-alpr-http-wrapper
    restart: unless-stopped
    image: sclaflin/open-alpr-http-wrapper:latest
    ports:
      - 3000:3000
  plate-minder-web:
    container_name: plate-minder-web
    image: sclaflin/plate-minder-web:latest
    restart: unless-stopped
    environment:
      - PLATE_MINDER_URL=http://XXXX:4000
    ports:
      - 8080:80
```

Stack screenshot from portainer
![image](https://user-images.githubusercontent.com/99711869/154004155-808aa5fc-b539-46ca-836e-824d083f0dae.png)
